data:
  plain: 16
  key: 16
  cipher: 16
  N: 16
---
alice:
  depth: 5
  hidden: 64
---
bob:
  depth: 5
  hidden: 64
  end_bit: 1.0
---
eve:
  depth: 5
  hidden: 64
  end_bit: 1.5
---
train:
  epochs: 500
  batch_size: 1024
  num_workers: 8
  steps: [250, 2] # steps per epoch for train/val
  adam:
    lr: 0.0012
---
log:
  log_dir: 'logs'
  validation: 1
